### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by tomaskikutis** [geordiemhall/rework-namespace-css#3]
**Code used:**

```
var gulp = require("gulp");
var rework = require('rework')
rework.namespace = require('rework-namespace-css')

return gulp.src('./style.css')
    .pipe(rework(rework.namespace({ selector: '.gmh', class: 'gmh-' })))
    .pipe(gulp.dest('dist/styles'))
```

**Response from console:**

```
C:\Users\myUser\Desktop\myFolder>node test.js

C:\Users\myUser\Desktop\myFolder\node_modules\css\lib\parse\index.js:130
    css = css.slice(str.length);
              ^
TypeError: Object function prefix(style) {

                function prefixSelector(selector){

                        var sel = selector

                        if (opts.namespaceBody !== false){

                                // Replace body with .body
                                sel = sel.replace(regBody, function(s){
                                        return s.replace('body', '.body')
                                })

                        }

                        if (opts.namespaceHtml !== false){

                                // Replace html with .html
                                sel = sel.replace(regHtml, function(s){
                                        return s.replace('html', '.html')
                                })

                        }

                        if (opts.selector){

                                var root = opts.root || 'html'

                                // TODO: This method would only replace the firs
t instance of root,
                                // so there is a rare bug when there are two cla
sses that both contain root.
                                // eg. if root is 'html' and an element has the
class .html5.html

                                // Add prefix to selector, adding it to the .htm
l part instead of prepending if needed
                                if (sel.indexOf(root) >= 0){
                                        sel = sel.replace(root, root + opts.sele
ctor)
                                } else {
                                        sel = opts.selector + ' ' + sel
                                }

                        }

                        return sel

                }

                function prefixClasses(selector){

                        return selector.split('.').join('.'+(opts.class || ''))

                }

                // Walk all styles
                walk(style, function(rule, node) {

                        // Don't touch keyframes or font-face
                        if (!rule.selectors || rule.selectors.toString().indexOf
('@') >= 0)
                                return rule;

                        rule.selectors = rule.selectors.map(function(selector) {

                                return prefixSelector(prefixClasses(selector))
                        });

                });

        } has no method 'slice'
    at match (C:\Users\myUser\Desktop\myFolder\node_modules\css\lib\parse\index.js:1
30:15)
    at whitespace (C:\Users\myUser\Desktop\myFolder\node_modules\css\lib\parse\index
.js:139:5)
    at rules (C:\Users\myUser\Desktop\myFolder\node_modules\css\lib\parse\index.js:1
09:5)
    at stylesheet (C:\Users\myUser\Desktop\myFolder\node_modules\css\lib\parse\index
.js:81:16)
    at module.exports (C:\Users\myUser\Desktop\myFolder\node_modules\css\lib\parse\i
ndex.js:559:20)
    at rework (C:\Users\myUser\Desktop\myFolder\node_modules\rework\index.js:27:21)
    at Object.<anonymous> (C:\Users\myUser\Desktop\myFolder\test.js:19:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

C:\Users\myUser\Desktop\myFolder>
```

**Comment by james-peel** [comment]
Did you find a solution for this @tomaskikutis ?

I'm having the same issue.

**Comment by tomaskikutis** [comment]
@james-peel I had very simplistic problem and built my own solution and didn't researched this library much :) What are you trying to accomplish ? I might be able to recommend something

**Comment by james-peel** [comment]
We're dealing with a lot of external scss libraries and need to namespace them without changing the source. @tomaskikutis 

Obviously we can .class { @import file.css } but that wraps everything including fonts, animations etc.

Gulp/node task seems the better solution.

**Comment by tomaskikutis** [comment]
@james-peel  I had a similar goal using less. I've wrote a small task using gulp-tap plugin.

Let's say we have a file:

```
  @import "grids";

  @import "buttons";

  //imports finished

  .component {
    background: red;
  }
```

What I do is take a file and put it all under namespace which has classname of filename. If environment is development I put imports under namespace, if production I split the string by my comment "//imports finished" and don't put imports under namespace for performance.

Here's my little snippet of how I did that:

```
gulp.task('less', function () {
	gulp.src('./styles/**/*.less')

		.pipe(tap(function(file){
			var wrapString = function(string){
				return "." + getFilenameFromPath(file.path) + "{" + string + "}";
			}

			if(env === "prod"){

				var importantArr = file.contents.toString().split("// imports finished!");

				file.contents = new Buffer( importantArr[0] + wrapString(importantArr[1]) );
			}
			else {
				file.contents = new Buffer( wrapString(file.contents.toString() ) );
			}

		}))
		.pipe(less())
		.pipe(concat("result.css"))
		.pipe(gulp.dest('./compiledCSS'))
});
```

**Comment by mbutsykin** [comment]
Try to use `gulp-rework` instead of `rework` :)
